######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : averageratioevent_3_ID0000027.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7f0ce36e-30b0-430c-be9b-bd1a8b90f66c PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=averageratioevent_3_ID0000027 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161129T232030+0000//00/00/averageratioevent_3_ID0000027.err
executable = /home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161129T232030+0000/00/00/averageratioevent_3_ID0000027.sh
initialdir = /home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/work/ubuntu/pegasus/example_workflow/20161129T232030+0000
log = /home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161129T232030+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161129T232030+0000//00/00/averageratioevent_3_ID0000027.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 70
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_AverageRatioEvent_3.py,example_workflow-averageratioevent_3-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161129T232030+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7f0ce36e-30b0-430c-be9b-bd1a8b90f66c"
+pegasus_wf_uuid = "7f0ce36e-30b0-430c-be9b-bd1a8b90f66c"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161129T232030+0000"
+pegasus_wf_xformation = "example_workflow::averageratioevent_3:1.0"
+pegasus_wf_dax_job_id = "ID0000027"
+pegasus_wf_dag_job_id = "averageratioevent_3_ID0000027"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
