######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : analysisevent_0_ID0000015.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=37199ae2-5179-4bad-b211-d928b5b17c5b PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=analysisevent_0_ID0000015 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161206T025446+0000//00/00/analysisevent_0_ID0000015.err
executable = /home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161206T025446+0000/00/00/analysisevent_0_ID0000015.sh
initialdir = /home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20161206T025446+0000
log = /home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161206T025446+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161206T025446+0000//00/00/analysisevent_0_ID0000015.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 80
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Analysis_AverageEvent_0.py,example_workflow-analysisevent_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/8_0_workflow_full_10files_primary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161206T025446+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "37199ae2-5179-4bad-b211-d928b5b17c5b"
+pegasus_wf_uuid = "37199ae2-5179-4bad-b211-d928b5b17c5b"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161206T025446+0000"
+pegasus_wf_xformation = "example_workflow::analysisevent_0:1.0"
+pegasus_wf_dax_job_id = "ID0000015"
+pegasus_wf_dag_job_id = "analysisevent_0_ID0000015"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
