######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : init_0_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=22c4b6c1-8d48-4a78-b5dd-6716364ceacb PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=init_0_ID0000001 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/dags/ubuntu/pegasus/example_workflow/20170127T125459+0000//00/00/init_0_ID0000001.err
executable = /home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/dags/ubuntu/pegasus/example_workflow/20170127T125459+0000/00/00/init_0_ID0000001.sh
initialdir = /home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/work/ubuntu/pegasus/example_workflow/20170127T125459+0000
log = /home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/dags/ubuntu/pegasus/example_workflow/20170127T125459+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/dags/ubuntu/pegasus/example_workflow/20170127T125459+0000//00/00/init_0_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = wikiflow-init_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/wikiflow/ok/9_1_wikiflow_1sh_1s_noannot_sec_wm1/dags/ubuntu/pegasus/example_workflow/20170127T125459+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "22c4b6c1-8d48-4a78-b5dd-6716364ceacb"
+pegasus_wf_uuid = "22c4b6c1-8d48-4a78-b5dd-6716364ceacb"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20170127T125459+0000"
+pegasus_wf_xformation = "wikiflow::init_0:1.0"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "init_0_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
