######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : taskevent_4_ID0000010.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=9a25b9f3-2015-4dd6-86f5-4050c3877ffe PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=taskevent_4_ID0000010 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161107T152502+0000//00/00/taskevent_4_ID0000010.err
executable = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161107T152502+0000/00/00/taskevent_4_ID0000010.sh
initialdir = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/work/ubuntu/pegasus/example_workflow/20161107T152502+0000
log = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161107T152502+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161107T152502+0000//00/00/taskevent_4_ID0000010.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-taskevent_4-1.0,ConfigDB_TaskEvent_4.py,ConfigDB_Task_StatsCPUMemory_4.py,ConfigDB_Task_GeneralInfo_4.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161107T152502+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "9a25b9f3-2015-4dd6-86f5-4050c3877ffe"
+pegasus_wf_uuid = "9a25b9f3-2015-4dd6-86f5-4050c3877ffe"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161107T152502+0000"
+pegasus_wf_xformation = "example_workflow::taskevent_4:1.0"
+pegasus_wf_dax_job_id = "ID0000010"
+pegasus_wf_dag_job_id = "taskevent_4_ID0000010"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
