######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : init_0_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=59633164-3b62-400a-9f00-b125ea40199d PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=init_0_ID0000001 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T193523+0000//00/00/init_0_ID0000001.err
executable = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T193523+0000/00/00/init_0_ID0000001.sh
initialdir = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/work/ubuntu/pegasus/example_workflow/20161108T193523+0000
log = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T193523+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T193523+0000//00/00/init_0_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-init_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/1-secondary-w1/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T193523+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "59633164-3b62-400a-9f00-b125ea40199d"
+pegasus_wf_uuid = "59633164-3b62-400a-9f00-b125ea40199d"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161108T193523+0000"
+pegasus_wf_xformation = "example_workflow::init_0:1.0"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "init_0_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
