######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : create_dir_example_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=d5ab8469-e1a5-4317-8518-d5e2ca18ce90 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=create_dir_example_workflow_0_local PEGASUS_SITE=local "
copy_to_spool = false
error = /home/ubuntu/wikiflow/new/11_1_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170124T231530+0000//00/00/create_dir_example_workflow_0_local.err
executable = /usr/bin/pegasus-transfer
input = /home/ubuntu/wikiflow/new/11_1_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170124T231530+0000//00/00/create_dir_example_workflow_0_local.in
log = /home/ubuntu/wikiflow/new/11_1_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170124T231530+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/wikiflow/new/11_1_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170124T231530+0000//00/00/create_dir_example_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "d5ab8469-e1a5-4317-8518-d5e2ca18ce90"
+pegasus_wf_uuid = "d5ab8469-e1a5-4317-8518-d5e2ca18ce90"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20170124T231530+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_example_workflow_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
