######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : init_0_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=ef4533bc-4a2d-4d1c-898e-79da99aa5db7 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=init_0_ID0000001 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000/init_0_ID0000001.err
executable = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000/init_0_ID0000001.sh
initialdir = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/work/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000
log = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000/init_0_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-init_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/8_workflow_full_10files_primary_1sh_annot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T004344+0000/pegasus-worker-4.6.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "ef4533bc-4a2d-4d1c-898e-79da99aa5db7"
+pegasus_wf_uuid = "ef4533bc-4a2d-4d1c-898e-79da99aa5db7"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160518T004344+0000"
+pegasus_wf_xformation = "example_workflow::init_0:1.0"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "init_0_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
