######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : calculateratio_8_ID0000023.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=2b96acf1-8651-43b0-8b4d-b841ecbf0a77 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=calculateratio_8_ID0000023 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T225102+0000//00/00/calculateratio_8_ID0000023.err
executable = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T225102+0000/00/00/calculateratio_8_ID0000023.sh
initialdir = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/work/ubuntu/pegasus/example_workflow/20161108T225102+0000
log = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T225102+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T225102+0000//00/00/calculateratio_8_ID0000023.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Calc_StatsCPUMemory_8.py,ConfigDB_Calc_TaskEvent_8.py,ConfigDB_Calc_TEInfo_8.py,example_workflow-calculateratio_8-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/2-secondary-wmajority/10_2_workflow_full_10files_secondary_wmj_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161108T225102+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "2b96acf1-8651-43b0-8b4d-b841ecbf0a77"
+pegasus_wf_uuid = "2b96acf1-8651-43b0-8b4d-b841ecbf0a77"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161108T225102+0000"
+pegasus_wf_xformation = "example_workflow::calculateratio_8:1.0"
+pegasus_wf_dax_job_id = "ID0000023"
+pegasus_wf_dag_job_id = "calculateratio_8_ID0000023"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
