######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : stage_worker_local_example_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3154a660-3f37-439b-a2a7-d117d9c4263b PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=stage_worker_local_example_workflow_0_local PEGASUS_SITE=local "
arguments = " --threads 2 "
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T041744+0000/stage_worker_local_example_workflow_0_local.err
executable = /usr/bin/../bin/pegasus-transfer
input = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T041744+0000/stage_worker_local_example_workflow_0_local.in
log = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T041744+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T041744+0000/stage_worker_local_example_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 700
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3154a660-3f37-439b-a2a7-d117d9c4263b"
+pegasus_wf_uuid = "3154a660-3f37-439b-a2a7-d117d9c4263b"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160510T041744+0000"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_worker_local_example_workflow_0_local"
+pegasus_job_class = 2
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
