######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : stage_in_local_local_2_1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=73e61419-f334-41c9-96d0-d8dffd258f42 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=stage_in_local_local_2_1 PEGASUS_SITE=local "
arguments = " -n pegasus::transfer -N null -i - -R local  -L example_workflow -T 2016-12-09T16:18:51+00:00 /usr/bin/../bin/pegasus-transfer  --threads 2 "
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/7_0_workflow_full_10files_primary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161209T161851+0000//00/00/stage_in_local_local_2_1.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/ubuntu/more_data/more_more_data/7_0_workflow_full_10files_primary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161209T161851+0000//00/00/stage_in_local_local_2_1.in
log = /home/ubuntu/more_data/more_more_data/7_0_workflow_full_10files_primary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161209T161851+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/7_0_workflow_full_10files_primary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161209T161851+0000//00/00/stage_in_local_local_2_1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 700
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "73e61419-f334-41c9-96d0-d8dffd258f42"
+pegasus_wf_uuid = "73e61419-f334-41c9-96d0-d8dffd258f42"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161209T161851+0000"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_in_local_local_2_1"
+pegasus_job_class = 2
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
