######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : calculateratio_2_ID0000011.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=bb1c75d9-e2f1-4f9d-bcc1-f30c8f5b4f89 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=calculateratio_2_ID0000011 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20170110T094728+0000//00/00/calculateratio_2_ID0000011.err
executable = /home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20170110T094728+0000/00/00/calculateratio_2_ID0000011.sh
initialdir = /home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20170110T094728+0000
log = /home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20170110T094728+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20170110T094728+0000//00/00/calculateratio_2_ID0000011.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Calc_TaskEvent_2.py,example_workflow-calculateratio_2-1.0,ConfigDB_Calc_TEInfo_2.py,ConfigDB_Calc_StatsCPUMemory_2.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/8_1_workflow_full_10files_secondary_w1_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20170110T094728+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "bb1c75d9-e2f1-4f9d-bcc1-f30c8f5b4f89"
+pegasus_wf_uuid = "bb1c75d9-e2f1-4f9d-bcc1-f30c8f5b4f89"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20170110T094728+0000"
+pegasus_wf_xformation = "example_workflow::calculateratio_2:1.0"
+pegasus_wf_dax_job_id = "ID0000011"
+pegasus_wf_dag_job_id = "calculateratio_2_ID0000011"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
