######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : create_dir_example_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=4dc40bc0-e130-4dfb-a475-0075d7f1773b PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=create_dir_example_workflow_0_local PEGASUS_SITE=local "
copy_to_spool = false
error = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/2-secondary-wmajority/8_2_workflow_full_10files_secondary_wmj_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161026T064002+0000//00/00/create_dir_example_workflow_0_local.err
executable = /usr/bin/pegasus-transfer
input = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/2-secondary-wmajority/8_2_workflow_full_10files_secondary_wmj_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161026T064002+0000//00/00/create_dir_example_workflow_0_local.in
log = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/2-secondary-wmajority/8_2_workflow_full_10files_secondary_wmj_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161026T064002+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/2-secondary-wmajority/8_2_workflow_full_10files_secondary_wmj_1sh_3rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161026T064002+0000//00/00/create_dir_example_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "4dc40bc0-e130-4dfb-a475-0075d7f1773b"
+pegasus_wf_uuid = "4dc40bc0-e130-4dfb-a475-0075d7f1773b"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161026T064002+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_example_workflow_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
