######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : create_dir_example_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=99f1db06-076d-4986-bafb-efc729154748 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=create_dir_example_workflow_0_local PEGASUS_SITE=local "
copy_to_spool = false
error = /home/elaine.n.watanabe/sciwonc-dataflow-examples/full_postgres/workflow_full_10files_primary_nosh_nors_opt_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160426T215842+0000/create_dir_example_workflow_0_local.err
executable = /usr/bin/pegasus-transfer
input = /home/elaine.n.watanabe/sciwonc-dataflow-examples/full_postgres/workflow_full_10files_primary_nosh_nors_opt_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160426T215842+0000/create_dir_example_workflow_0_local.in
log = /home/elaine.n.watanabe/sciwonc-dataflow-examples/full_postgres/workflow_full_10files_primary_nosh_nors_opt_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160426T215842+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sciwonc-dataflow-examples/full_postgres/workflow_full_10files_primary_nosh_nors_opt_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160426T215842+0000/create_dir_example_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "99f1db06-076d-4986-bafb-efc729154748"
+pegasus_wf_uuid = "99f1db06-076d-4986-bafb-efc729154748"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160426T215842+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_example_workflow_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
