######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : averageratio_4_ID0000018.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=644ac1a2-bfd7-463b-b81b-b462d81c2891 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=averageratio_4_ID0000018 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000/averageratio_4_ID0000018.err
executable = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000/averageratio_4_ID0000018.sh
initialdir = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/work/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000
log = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000/averageratio_4_ID0000018.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-averageratio_4-1.0,ConfigDB_Average_4.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160521T031622+0000/pegasus-worker-4.6.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "644ac1a2-bfd7-463b-b81b-b462d81c2891"
+pegasus_wf_uuid = "644ac1a2-bfd7-463b-b81b-b462d81c2891"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160521T031622+0000"
+pegasus_wf_xformation = "example_workflow::averageratio_4:1.0"
+pegasus_wf_dax_job_id = "ID0000018"
+pegasus_wf_dag_job_id = "averageratio_4_ID0000018"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
