######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : maxminratio_0_ID0000023.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=7285b927-b52a-4923-a148-972390a5fd7d PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=maxminratio_0_ID0000023 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000/maxminratio_0_ID0000023.err
executable = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000/maxminratio_0_ID0000023.sh
initialdir = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/work/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000
log = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000/maxminratio_0_ID0000023.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-maxminratio_0-1.0,ConfigDB_MaxMin_0.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T015915+0000/pegasus-worker-4.6.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "7285b927-b52a-4923-a148-972390a5fd7d"
+pegasus_wf_uuid = "7285b927-b52a-4923-a148-972390a5fd7d"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160522T015915+0000"
+pegasus_wf_xformation = "example_workflow::maxminratio_0:1.0"
+pegasus_wf_dax_job_id = "ID0000023"
+pegasus_wf_dag_job_id = "maxminratio_0_ID0000023"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
