######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : clean_up_local_level_5_1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=66ccd2a4-919e-4486-bd23-760802f7d4b8 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=clean_up_local_level_5_1 PEGASUS_SITE=local "
arguments = " -n pegasus::cleanup -N null -i - -R local  -L example_workflow -T 2016-05-22T03:13:10+00:00 /usr/bin/../bin/pegasus-transfer "
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T031310+0000/clean_up_local_level_5_1.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T031310+0000/clean_up_local_level_5_1.in
log = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T031310+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/10_workflow_full_10files_primary_3sh_annot_with_proj_3s_hs/dags/elaine.n.watanabe/pegasus/example_workflow/20160522T031310+0000/clean_up_local_level_5_1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "66ccd2a4-919e-4486-bd23-760802f7d4b8"
+pegasus_wf_uuid = "66ccd2a4-919e-4486-bd23-760802f7d4b8"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160522T031310+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_5_1"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
