######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : clean_up_local_level_9_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=96cb7623-c77b-4668-b26c-687e9d45e6f6 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=clean_up_local_level_9_0 PEGASUS_SITE=local "
arguments = " -n pegasus::cleanup -N null -i - -R local  -L example_workflow -T 2016-10-25T02:28:43+00:00 /usr/bin/../bin/pegasus-transfer "
copy_to_spool = false
error = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/1-secondary-w1/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T022843+0000//00/00/clean_up_local_level_9_0.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/1-secondary-w1/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T022843+0000//00/00/clean_up_local_level_9_0.in
log = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/1-secondary-w1/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T022843+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/3-mongodb-1sh-3rp-small/1-secondary-w1/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T022843+0000//00/00/clean_up_local_level_9_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "96cb7623-c77b-4668-b26c-687e9d45e6f6"
+pegasus_wf_uuid = "96cb7623-c77b-4668-b26c-687e9d45e6f6"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161025T022843+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_9_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
