######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : calculateratio_0_ID0000009.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=0e666bcc-6346-4918-b1ce-00f3e687c14a PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=calculateratio_0_ID0000009 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T030046+0000//00/00/calculateratio_0_ID0000009.err
executable = /home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T030046+0000/00/00/calculateratio_0_ID0000009.sh
initialdir = /home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20161025T030046+0000
log = /home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T030046+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T030046+0000//00/00/calculateratio_0_ID0000009.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Calc_StatsCPUMemory_0.py,example_workflow-calculateratio_0-1.0,ConfigDB_Calc_TaskEvent_0.py,ConfigDB_Calc_TEInfo_0.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/0_experiments/2-mongodb-1sh-1rp-small/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161025T030046+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "0e666bcc-6346-4918-b1ce-00f3e687c14a"
+pegasus_wf_uuid = "0e666bcc-6346-4918-b1ce-00f3e687c14a"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161025T030046+0000"
+pegasus_wf_xformation = "example_workflow::calculateratio_0:1.0"
+pegasus_wf_dax_job_id = "ID0000009"
+pegasus_wf_dag_job_id = "calculateratio_0_ID0000009"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
