######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : taskevent_1_ID0000007.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3ce07384-23e1-4d90-9b28-d957c028b309 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=taskevent_1_ID0000007 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161203T121239+0000//00/00/taskevent_1_ID0000007.err
executable = /home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161203T121239+0000/00/00/taskevent_1_ID0000007.sh
initialdir = /home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20161203T121239+0000
log = /home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161203T121239+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161203T121239+0000//00/00/taskevent_1_ID0000007.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Task_StatsCPUMemory_1.py,ConfigDB_TaskEvent_1.py,example_workflow-taskevent_1-1.0,ConfigDB_Task_GeneralInfo_1.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/6_workflow_full_10files_primary_1sh_1rs_with_annot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161203T121239+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3ce07384-23e1-4d90-9b28-d957c028b309"
+pegasus_wf_uuid = "3ce07384-23e1-4d90-9b28-d957c028b309"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161203T121239+0000"
+pegasus_wf_xformation = "example_workflow::taskevent_1:1.0"
+pegasus_wf_dax_job_id = "ID0000007"
+pegasus_wf_dag_job_id = "taskevent_1_ID0000007"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
