######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : cleanup_example_workflow_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=b00ce3d8-0cdb-4202-a54c-6721ca5f3816 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=cleanup_example_workflow_0_local PEGASUS_SITE=local "
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/4_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T153143+0000/cleanup_example_workflow_0_local.err
executable = /usr/bin/pegasus-transfer
input = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/4_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T153143+0000/cleanup_example_workflow_0_local.in
log = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/4_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T153143+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/4_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160518T153143+0000/cleanup_example_workflow_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "b00ce3d8-0cdb-4202-a54c-6721ca5f3816"
+pegasus_wf_uuid = "b00ce3d8-0cdb-4202-a54c-6721ca5f3816"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160518T153143+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_example_workflow_0_local"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
