######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : averageratioevent_0_ID0000008.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=35e2a61a-c9ae-413c-8040-6b488fa7ec47 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=averageratioevent_0_ID0000008 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161219T002720+0000//00/00/averageratioevent_0_ID0000008.err
executable = /home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161219T002720+0000/00/00/averageratioevent_0_ID0000008.sh
initialdir = /home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20161219T002720+0000
log = /home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161219T002720+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161219T002720+0000//00/00/averageratioevent_0_ID0000008.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 70
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-averageratioevent_0-1.0,ConfigDB_AverageRatioEvent_0.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/9_2_workflow_full_10files_secondary_with_cons_nosh_nors_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161219T002720+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "35e2a61a-c9ae-413c-8040-6b488fa7ec47"
+pegasus_wf_uuid = "35e2a61a-c9ae-413c-8040-6b488fa7ec47"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161219T002720+0000"
+pegasus_wf_xformation = "example_workflow::averageratioevent_0:1.0"
+pegasus_wf_dax_job_id = "ID0000008"
+pegasus_wf_dag_job_id = "averageratioevent_0_ID0000008"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
