######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : clean_up_local_level_4_1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=fca81424-23e2-4c16-acc9-450573a5952c PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=clean_up_local_level_4_1 PEGASUS_SITE=local "
arguments = " -n pegasus::cleanup -N null -i - -R local  -L example_workflow -T 2016-05-10T12:51:02+00:00 /usr/bin/../bin/pegasus-transfer "
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T125102+0000/clean_up_local_level_4_1.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T125102+0000/clean_up_local_level_4_1.in
log = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T125102+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/1-postgres/1_workflow_full_10files_primary_nosh_nors_noannot_with_proj_1s/dags/elaine.n.watanabe/pegasus/example_workflow/20160510T125102+0000/clean_up_local_level_4_1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "fca81424-23e2-4c16-acc9-450573a5952c"
+pegasus_wf_uuid = "fca81424-23e2-4c16-acc9-450573a5952c"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160510T125102+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_4_1"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
