######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : averageratio_6_ID0000020.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=50b24385-ea66-4836-bb2f-81e63641dce7 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=averageratio_6_ID0000020 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/dags/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000/averageratio_6_ID0000020.err
executable = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/dags/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000/averageratio_6_ID0000020.sh
initialdir = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/work/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000
log = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/dags/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/dags/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000/averageratio_6_ID0000020.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-averageratio_6-1.0,ConfigDB_Average_6.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/elaine.n.watanabe/sbbd/experiments/4-mongodb-rp-3sh/11_workflow_full_10files_primary_3sh_annot_with_proj_3s_rg/dags/elaine.n.watanabe/pegasus/example_workflow/20160523T030841+0000/pegasus-worker-4.6.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "50b24385-ea66-4836-bb2f-81e63641dce7"
+pegasus_wf_uuid = "50b24385-ea66-4836-bb2f-81e63641dce7"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160523T030841+0000"
+pegasus_wf_xformation = "example_workflow::averageratio_6:1.0"
+pegasus_wf_dax_job_id = "ID0000020"
+pegasus_wf_dag_job_id = "averageratio_6_ID0000020"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
