######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : calculateratio_1_ID0000016.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=5ecc02c7-8840-4313-b343-35999be6b991 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=calculateratio_1_ID0000016 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161124T202240+0000//00/00/calculateratio_1_ID0000016.err
executable = /home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161124T202240+0000/00/00/calculateratio_1_ID0000016.sh
initialdir = /home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/work/ubuntu/pegasus/example_workflow/20161124T202240+0000
log = /home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161124T202240+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161124T202240+0000//00/00/calculateratio_1_ID0000016.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Calc_TEInfo_1.py,ConfigDB_Calc_StatsCPUMemory_1.py,ConfigDB_Calc_TaskEvent_1.py,example_workflow-calculateratio_1-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/10_1_workflow_full_10files_secondary_w1_3sh_3rs_with_annot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161124T202240+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "5ecc02c7-8840-4313-b343-35999be6b991"
+pegasus_wf_uuid = "5ecc02c7-8840-4313-b343-35999be6b991"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161124T202240+0000"
+pegasus_wf_xformation = "example_workflow::calculateratio_1:1.0"
+pegasus_wf_dax_job_id = "ID0000016"
+pegasus_wf_dag_job_id = "calculateratio_1_ID0000016"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
