######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : sessioncompute_0_ID0000003.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=9cc9664b-92da-4d38-a832-b0601266ec8f PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=sessioncompute_0_ID0000003 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/dags/ubuntu/pegasus/example_workflow/20170121T153700+0000//00/00/sessioncompute_0_ID0000003.err
executable = /home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/dags/ubuntu/pegasus/example_workflow/20170121T153700+0000/00/00/sessioncompute_0_ID0000003.sh
initialdir = /home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/work/ubuntu/pegasus/example_workflow/20170121T153700+0000
log = /home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/dags/ubuntu/pegasus/example_workflow/20170121T153700+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/dags/ubuntu/pegasus/example_workflow/20170121T153700+0000//00/00/sessioncompute_0_ID0000003.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_SessionCompute_0.py,wikiflow-sessioncompute_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/wikiflow/7_2_wikiflow_1sh_1s_noannot_wmj/dags/ubuntu/pegasus/example_workflow/20170121T153700+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "9cc9664b-92da-4d38-a832-b0601266ec8f"
+pegasus_wf_uuid = "9cc9664b-92da-4d38-a832-b0601266ec8f"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20170121T153700+0000"
+pegasus_wf_xformation = "wikiflow::sessioncompute_0:1.0"
+pegasus_wf_dax_job_id = "ID0000003"
+pegasus_wf_dag_job_id = "sessioncompute_0_ID0000003"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
