######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : taskevent_2_ID0000008.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=dd7f987b-92db-4113-86d8-f54e14e0e0e5 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=taskevent_2_ID0000008 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161127T171406+0000//00/00/taskevent_2_ID0000008.err
executable = /home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161127T171406+0000/00/00/taskevent_2_ID0000008.sh
initialdir = /home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/work/ubuntu/pegasus/example_workflow/20161127T171406+0000
log = /home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161127T171406+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161127T171406+0000//00/00/taskevent_2_ID0000008.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_Task_GeneralInfo_2.py,example_workflow-taskevent_2-1.0,ConfigDB_Task_StatsCPUMemory_2.py,ConfigDB_TaskEvent_2.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/10_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_range/dags/ubuntu/pegasus/example_workflow/20161127T171406+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "dd7f987b-92db-4113-86d8-f54e14e0e0e5"
+pegasus_wf_uuid = "dd7f987b-92db-4113-86d8-f54e14e0e0e5"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161127T171406+0000"
+pegasus_wf_xformation = "example_workflow::taskevent_2:1.0"
+pegasus_wf_dax_job_id = "ID0000008"
+pegasus_wf_dag_job_id = "taskevent_2_ID0000008"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
