######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : init_0_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=16650a51-cf02-4d6b-842d-9817675a13a7 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=init_0_ID0000001 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161214T192117+0000//00/00/init_0_ID0000001.err
executable = /home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161214T192117+0000/00/00/init_0_ID0000001.sh
initialdir = /home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/work/ubuntu/pegasus/example_workflow/20161214T192117+0000
log = /home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161214T192117+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161214T192117+0000//00/00/init_0_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-init_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/more_data/more_more_data/7_1_workflow_full_10files_secondary_w1_1sh_3rs_noannot_with_proj_3s/dags/ubuntu/pegasus/example_workflow/20161214T192117+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "16650a51-cf02-4d6b-842d-9817675a13a7"
+pegasus_wf_uuid = "16650a51-cf02-4d6b-842d-9817675a13a7"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161214T192117+0000"
+pegasus_wf_xformation = "example_workflow::init_0:1.0"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "init_0_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
