######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : statscpumemory_0_ID0000003.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=61defb9b-da83-43dc-b915-17215da3a312 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=statscpumemory_0_ID0000003 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161108T164747+0000//00/00/statscpumemory_0_ID0000003.err
executable = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161108T164747+0000/00/00/statscpumemory_0_ID0000003.sh
initialdir = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/work/ubuntu/pegasus/example_workflow/20161108T164747+0000
log = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161108T164747+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161108T164747+0000//00/00/statscpumemory_0_ID0000003.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-statscpumemory_0-1.0,ConfigDB_StatsCPUMemory_0.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/0_experiments/4-mongodb-3sh-3rp-small/0-primary-w1/11_0_workflow_full_10files_primary_3sh_3rs_noannot_with_proj_3s_hash/dags/ubuntu/pegasus/example_workflow/20161108T164747+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "61defb9b-da83-43dc-b915-17215da3a312"
+pegasus_wf_uuid = "61defb9b-da83-43dc-b915-17215da3a312"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20161108T164747+0000"
+pegasus_wf_xformation = "example_workflow::statscpumemory_0:1.0"
+pegasus_wf_dax_job_id = "ID0000003"
+pegasus_wf_dag_job_id = "statscpumemory_0_ID0000003"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
