######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : maxminratio_0_ID0000007.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=b838d661-fd19-4568-bbe6-59c7c3995765 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=maxminratio_0_ID0000007 PEGASUS_SITE=condorpool "
+TransferOutput = ""
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000/maxminratio_0_ID0000007.err
executable = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000/maxminratio_0_ID0000007.sh
initialdir = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/work/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000
log = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000/maxminratio_0_ID0000007.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = example_workflow-maxminratio_0-1.0,ConfigDB_MaxMin_0.py,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/elaine.n.watanabe/sbbd/experiments/2-mongodb-norp-nosh/5_workflow_full_10files_primary_nosh_nors_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160515T020500+0000/pegasus-worker-4.6.0-x86_64_ubuntu_14.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "b838d661-fd19-4568-bbe6-59c7c3995765"
+pegasus_wf_uuid = "b838d661-fd19-4568-bbe6-59c7c3995765"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160515T020500+0000"
+pegasus_wf_xformation = "example_workflow::maxminratio_0:1.0"
+pegasus_wf_dax_job_id = "ID0000007"
+pegasus_wf_dag_job_id = "maxminratio_0_ID0000007"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
