######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : computeusergroup_0_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=afb91014-4390-40f2-9af4-28140924a530 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=computeusergroup_0_ID0000002 PEGASUS_SITE=condorpool "
copy_to_spool = false
error = /home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170119T115746+0000//00/00/computeusergroup_0_ID0000002.err
executable = /home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170119T115746+0000/00/00/computeusergroup_0_ID0000002.sh
initialdir = /home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/work/ubuntu/pegasus/example_workflow/20170119T115746+0000
log = /home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170119T115746+0000/example_workflow-0.log
notification = NEVER
output = /home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170119T115746+0000//00/00/computeusergroup_0_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = ConfigDB_UserGroup_0.py,wikiflow-computeusergroup_0-1.0,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/ubuntu/wikiflow/ok/10_0_wikiflow_1sh_1s_annot/dags/ubuntu/pegasus/example_workflow/20170119T115746+0000/pegasus-worker-4.7.0-x86_64_ubuntu_14.tar.gz
transfer_output_files = ConfigDB_SessionCompute_1.py,ConfigDB_SessionCompute_7.py,ConfigDB_SessionCompute_4.py,ConfigDB_SessionCompute_0.py,ConfigDB_SessionCompute_2.py,ConfigDB_SessionCompute_6.py,ConfigDB_SessionCompute_3.py,ConfigDB_SessionCompute_5.py,ConfigDB_SessionCompute_8.py,
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "afb91014-4390-40f2-9af4-28140924a530"
+pegasus_wf_uuid = "afb91014-4390-40f2-9af4-28140924a530"
+pegasus_version = "4.7.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20170119T115746+0000"
+pegasus_wf_xformation = "wikiflow::computeusergroup_0:1.0"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "computeusergroup_0_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
