######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : example_workflow, Index = 0, Count = 1
# SUBMIT FILE NAME : stage_in_remote_local_2_1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3fc89746-b191-4b6b-a043-54d2e845a835 PEGASUS_WF_LABEL=example_workflow PEGASUS_DAG_JOB_ID=stage_in_remote_local_2_1 PEGASUS_SITE=local "
arguments = " -n pegasus::transfer -N null -i - -R local  -L example_workflow -T 2016-05-17T08:48:22+00:00 /usr/bin/../bin/pegasus-transfer  --threads 2 "
copy_to_spool = false
error = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/7_workflow_full_10files_primary_1sh_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160517T084823+0000/stage_in_remote_local_2_1.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/7_workflow_full_10files_primary_1sh_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160517T084823+0000/stage_in_remote_local_2_1.in
log = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/7_workflow_full_10files_primary_1sh_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160517T084823+0000/example_workflow-0.log
notification = NEVER
output = /home/elaine.n.watanabe/sbbd/experiments/3-mongodb-rp-1sh/7_workflow_full_10files_primary_1sh_noannot_with_proj_3s/dags/elaine.n.watanabe/pegasus/example_workflow/20160517T084823+0000/stage_in_remote_local_2_1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 700
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3fc89746-b191-4b6b-a043-54d2e845a835"
+pegasus_wf_uuid = "3fc89746-b191-4b6b-a043-54d2e845a835"
+pegasus_version = "4.6.0"
+pegasus_wf_name = "example_workflow-0"
+pegasus_wf_time = "20160517T084823+0000"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_in_remote_local_2_1"
+pegasus_job_class = 2
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
